-- ═══════════ PATCH 04 — ORG CHART ═══════════
--
-- `org_chart_nodes` came from the "Org Chart Info" sheet, which covers
-- leadership only and carries no tile level, department slug, photo, email or
-- project-manager flag. The org chart page needs all of those, so pointing it
-- at the table as it stood would have dropped ten people and flattened the
-- hierarchy.
--
-- This widens the table to hold everything the chart draws, then reloads it
-- from the richer hand-maintained source. After this the org chart reads from
-- the database like every other page, and PMs can edit it.
--
-- Run after patch-03. Safe to re-run.

begin;

-- ── the fields the chart needs ────────────────────────────────────────────
alter table public.org_chart_nodes
  add column if not exists node_key      text,      -- stable id used by the chart
  add column if not exists reports_to_key text,     -- parent's node_key
  add column if not exists dept_slug     text,      -- executive|records|enrollment|dean|digital
  add column if not exists level         integer,   -- 1 VP … 5 staff
  add column if not exists email         text,
  add column if not exists photo_url     text,
  add column if not exists is_pm         boolean not null default false,
  add column if not exists pm_position   text,      -- left|right, for PM tiles
  add column if not exists responsibilities text[],
  add column if not exists kpis          text[];

create unique index if not exists org_chart_nodes_key_idx
  on public.org_chart_nodes (node_key);

-- ── keep the sheet's narrative text, keyed by name ────────────────────────
create temporary table _sheet_text on commit drop as
  select lower(trim(name)) as name_key, stewardships, key_kpis,
         key_responsibilities, direct_reports
    from public.org_chart_nodes
   where stewardships is not null or key_kpis is not null;

delete from public.org_chart_nodes;

insert into public.org_chart_nodes (sort_order, node_key, name, role, employee_status, reports_to, reports_to_key, dept_slug, department, level, email, photo_url, link, is_pm, pm_position, responsibilities, kpis) values
  (1, 'vp', 'Ben Packer', 'Vice President of Student Services', 'FTE', null, null, 'executive', null, 1, 'bpacker@byupw.edu', '../photos/executive/vp.jpeg', null, false, null, '{"Executive oversight of all Student Services operations","Strategic direction for student support, enrollment, records, and digital operations","Budget and resource allocation across departments"}', '{"Overall student satisfaction scores","Student retention and completion rates","Operational efficiency across departments"}'),
  (2, 'mark-gefrom', 'Mark Gefrom', 'Director of Student Records, Registration & Support', 'FTE', null, 'vp', 'records', null, 2, 'mgefrom@byupw.edu', '../photos/records/mark-gefrom.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBpfBRqxg1FTqAoAyYTtdYhAQZ58j2DOREbCoKMFpxpPBY?e=WczgAk', false, null, '{"Registrar, student support, tech support oversight","Help center","Customer relations systems","Ticket systems"}', '{"All Records, Registration, and Support teams meeting or exceeding service-level agreements for response, resolution, QA, CSAT, and first contact resolution","Records, registration, and support department budget","Overall student autonomy (primary)","Overall student satisfaction (secondary)"}'),
  (3, 'alison-cundiff', 'Alison Cundiff', 'Director of Enrollment & Retention', 'FTE', null, 'vp', 'enrollment', null, 2, 'acundiff@byupw.edu', '../photos/enrollment/alison-cundiff.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAFhc5UkuwgTapnxWheHmYRAeUt6L6jGcomm-gS_hKDWbg?e=v2NPg4', false, null, '{"Enrollment services & mentoring oversight","Student retention and completion"}', '{"Enrollment & Retention budget","Enrollment, retention, completion (primary)","Overall student autonomy and satisfaction (secondary)"}'),
  (4, 'steven-thomas', 'Steven K. Thomas', 'Dean of Students', 'FTE', null, 'vp', 'dean', null, 2, 'sthomas@byupw.edu', '../photos/dean/steven-thomas.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAJCeQuk9fHTbFRX-_VINCFAXaStbvWN2DK4_tsSELnmmQ?e=UfES01', false, null, '{"Executive Oversight of Federally and Institutionally Mandated Student Service Offices","Institutional Policy Stewardship & Compliance (Title IX Coordintor, ADA/Section 504 Coordinator)","Crisis Governance & Risk Mitigation"}', '{"No material audit, legal, or accreditation findings attributable to Dean of Students governance","Annual DOS budget","Overall student satisfaction (primary)"}'),
  (5, 'jacob-adams', 'Jacob Adams', 'Director of Digital Operations', 'FTE', null, 'vp', 'digital', null, 2, 'jadams@byupw.edu', '../photos/digital/jacob-adams.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQA4Z3GLmjrRQ7VQBp_tH6EAAX8tlXHJ79We6G8lvZI-Z_s?e=hfmBx2', false, null, '{"Digital operations oversight","Application and implementation of emerging technologies","Strategy for Power BI, machine learning, agentic AI, and Companion teams","UX evaluation & impact review"}', '{"Overall Stakeholder CSAT","Digital Ops budget","Costs saved by customers due to Digital Ops technologies (secondary)","Overall student autonomy (secondary)","Overall student satisfaction (secondary)","Application Rate","Retention Rate","Completion Rate (Secondary)"}'),
  (6, 'brad-lester', 'Brad Lester', 'Senior Manager, Student Support', 'FTE', null, 'mark-gefrom', 'records', null, 3, 'blester@byupw.edu', '../photos/records/brad-lester.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCKoBX4HbZJRq7HLLXdBrCbAdvXS8PLZF0W8t-imhz4UV4?e=HLCnTw', false, null, '{"Inbound student support lead","Academic advising program"}', '{"Student support budget","Autonomy rate for student support cases"}'),
  (7, 'kari-johnson', 'Kari Johnson', 'Registrar', 'FTE', null, 'mark-gefrom', 'records', null, 3, 'karijohnson32@byupw.edu', '../photos/records/kari-johnson.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBkQUDPjDkJQqGJR2uD02GvAZ2F5T3reRUi0tmNHnatB8c?e=em7vc2', false, null, '{"Registration and Records lead","Academic record maintenance","Block/Term system and catalog data publishing"}', '{"Registrar budget","Autonomy for registrar processes and cases","Case CSAT for planning and registration"}'),
  (8, 'matthew-smith', 'Matthew Smith', 'Technical Support Manager', 'FTE', null, 'mark-gefrom', 'records', null, 3, 'msmith@byupw.edu', '../photos/records/matthew-smith.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQC6ZURvjEf_R4kbBaAAgIjGAaB-PHWFt8Afm--cDEFlV6M?e=Y0g1Xo', false, null, '{"Inbound tech support lead"}', '{"Tech support case resolution rate","Tech support costs","Autonomy rate for tech support cases"}'),
  (9, 'hilary-bagley', 'Hilary Bagley', 'Student Experience Coordinator', 'FTE', null, 'brad-lester', 'records', null, 4, 'hbagley@byupw.edu', '../photos/records/hilary-bagley.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAAwTC8MOIqQIkj0G04BRqGAc9Y9taAUl9NY_6ZfIDUJ4Y?e=hfFaGg', false, null, '{"Training, area collaboration, & partner communication","Media & Knowledge Base development","Student Support content accuracy","Student journey mapping"}', '{"Request-to-KB publish rate","Knowledge Base audit pass rate","Cost per KB Article Maintained","QA feedback cycle rate","QA calibration consistency rate","QA team lead feedback success rate","Cost per QA Evaluation"}'),
  (10, 'kim-overdiek', 'Kim Overdiek', 'Associate Registrar (Curriculum & Configuration)', 'FTE', null, 'kari-johnson', 'records', null, 4, 'kim.overdiek@byupw.edu', '../photos/records/kim-overdiek.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDHxfnyxJ_PTKTIYysDqssWAVj3YJCFsDb62MgYnRnRvfo?e=zcdOtl', false, null, '{"Policies & processes","Curriculum/catalog maintenance","Academic planning system configuration","Course registration process"}', '{"Process case resolution rate, QA, and CSAT","On-time catalog publishing and system configuration rates"}'),
  (11, 'tyson-bell', 'Tyson Bell', 'Associate Registrar (Transcripts & Graduation)', 'FTE', null, 'kari-johnson', 'records', null, 4, 'tbell1@byupw.edu', '../photos/records/tyson-bell.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQANGB82vwVpR7kWikzK32R6AcXDcnbDlXCI-F8G8MsOwZA?e=HYUBCa', false, null, '{"Student records","Transcripts","Graduation","Enrollment verification"}', '{"Records case resolution rate, QA, and CSAT"}'),
  (12, 'colby-warner', 'Colby Warner', 'Product Support Engineer', 'FTE', null, 'matthew-smith', 'records', null, 5, 'CWarner@byupw.edu', '../photos/records/colby-warner.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBaWG5YlOnKQrXGueyhBughAXBMduY1rLTdPM_7EobPwQo?e=e6Zd8q', false, null, '{"Tech support troubleshooting & resolution"}', '{"Escalated case resolution rate","Tech support case QA, CSAT, first contract resolution"}'),
  (13, 'alyssa-burrell', 'Alyssa Burrell', 'Student Support Coordinator (Phone Support)', 'FTE', null, 'brad-lester', 'records', null, 5, 'Burrell3@byupw.edu', '../photos/records/alyssa-burrell.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBwUBFZyWZaSLXU28SQe4_cAUirTYoW8S2Th63JomM1XhM?e=YVQEeX', false, null, '{"Phone support","General support"}', '{"General support case response and resolution rates","Phone support answer speed, handle rate, agent availability, QA, CSAT, and first contact resolution"}'),
  (14, 'kira-hayes', 'Kira Hayes', 'Consistency Coordinator (QA & Knowledge Base)', 'FTE', null, 'hilary-bagley', 'records', null, 5, 'khayes@byupw.edu', '../photos/records/kira-hayes.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCtk6Visur9S73CLrYxUHrpAd25rc-Xrtvfnt3SO0KwFLM?e=H5naai', false, null, '{"Ticketing QA","External Knowledge Base articles","Support agent onboarding and training"}', '{"KB publishing rate","QA evaluation completion rate","DSAT and critical violation delivery rate"}'),
  (15, 'angie-holt', 'Angie Holt', 'Graduation Coordinator', 'Contractor', null, 'tyson-bell', 'records', null, 5, 'angieholt@churchofjesuschrist.org', '../photos/records/angie-holt.jpg', null, false, null, '{"Graduation application","Diploma awarding process"}', '{"Graduation application case completion rate","Award processing rate","Number of rescinded degrees","Application and awarding QA"}'),
  (16, 'anne-owen', 'Anne E. Owen', 'Records & Transcript Coordinator', 'FTE', null, 'tyson-bell', 'records', null, 5, 'adavidso@byupw.edu', '../photos/records/anne-owen.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAEOXkjnBS2T5AgKHhw-KlEAXws8SAXw2fBBXWANGQ3-i8?e=frYZ29', false, null, '{"Grade changes","Academic exceptions","Transcript requests"}', '{"Process case completion rate","Process case QA, and CSAT","Transcript accuracy QA"}'),
  (17, 'cindi-putnam', 'Cindi C Putnam', 'Planning Coordinator', 'FTE', null, 'kim-overdiek', 'records', null, 5, 'cputnam@byupw.edu', '../photos/records/cindi-putnam.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDM5kWdtj6eTobfhfYTnaukATgc2h46N2asN0nMbPnj9eA?e=vikaN5', false, null, '{"Degree progress audit corrections"}', '{"Degree planning escalation case resolution rate, QA, and CSAT"}'),
  (18, 'daniel-zago', 'Daniel Zago', 'Curriculum and Registration Coordinator', 'Contractor', null, 'kim-overdiek', 'records', null, 5, 'danielnzago@churchofjesuschrist.org', '../photos/records/daniel-zago.jpg', null, false, null, '{"Curriculum/catalog maintenance","Course registration process support"}', '{"Catalog accuracy","Registration support case resolution rate"}'),
  (19, 'nikki-chambers', 'Nikki Jane Chambers', 'Enrollment Verification Specialist', 'FTT', null, 'tyson-bell', 'records', null, 5, 'NChambers@byupw.edu', '../photos/records/nikki-chambers.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBkohdpEKodQoL-ghZzzwCRAQKlxkR8j_9LVGL0oGq1t5Y?e=8brGcT', false, null, '{"Enrollment verification","Partner transfer evaluation","Apostilles","Student verification letters"}', '{"Enrollment verification and apostille completion rate","Enrollment verification QA, and CSAT","Apostille QA, and CSAT"}'),
  (20, 'trevor-shelton', 'Trevor Shelton', 'Senior Manager of Enrollment Services', 'FTE', null, 'alison-cundiff', 'enrollment', null, 3, 'tshelton@byupw.edu', '../photos/enrollment/trevor-shelton.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCVmNuaOp68SKhTnf_tOoajAX5JqDNZE3skdK_YOh1zQOg?e=cIHUdp', false, null, '{"Enrollment services lead","Enrollment funnel performance, strategy, and innovation"}', '{"Reduction of enrollment related support cases","Reduction of admissions tier 2 support cases"}'),
  (21, 'katelyn-graf', 'Katelyn Graf', 'Senior Manager of Retention', 'FTE', null, 'alison-cundiff', 'enrollment', null, 3, 'kgraf@byupw.edu', '../photos/enrollment/katelyn-graf.jpg', null, false, null, '{"Retention strategy and oversight"}', null),
  (22, 'kelley-richardson', 'Kelley Richardson', 'Mentoring Manager', 'FTE', null, 'katelyn-graf', 'enrollment', null, 4, 'KRichardson@byupw.edu', '../photos/enrollment/kelley-richardson.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDf11sIFIdKRpf47WFm_HrbAbXK5oADRJG7VjwmaQKoGEY?e=LfYtXd', false, null, '{"Mentoring program lead"}', '{"Mentor required action completion rate","Mentor interaction QA","Overall student autonomy (secondary)","Mentor CSAT","Retention rate contribution by mentors"}'),
  (23, 'rachel-kirk', 'Rachel Kirk', 'Enrollment Counseling Manager', 'FTE', null, 'trevor-shelton', 'enrollment', null, 4, 'Rhorton@byupw.edu', '../photos/enrollment/rachel-kirk.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAw0JzSy0-_SJwGTk9TEoL5AfQPAV9g6j-Z3Q3eUX_PAaY?e=flOOTM', false, null, '{"Enrollment Counseling team","Enrollment funnel performance & outcomes"}', '{"Application start to admission yield","Admission to registration yield","Registration to auto-drop yield"}'),
  (24, 'mandy-schwab', 'Mandy Schwab', 'Mentor Development Specialist', 'PTT', null, 'kelley-richardson', 'enrollment', null, 5, 'Mandraps@byupw.edu', '../photos/enrollment/mandy-schwab.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBy2LVzDoldRZisyIODLh8zAQMURc-jWPshlLW15i3qb1A?e=U7sRj2', false, null, '{"Mentoring program development"}', '{"Mentor interaction QA","Mentor CSAT"}'),
  (25, 'johanna-relkin', 'Joanna Relken', 'Mentor Operations Specialist', 'PTT', null, 'kelley-richardson', 'enrollment', null, 5, 'Joanna.Relken@byupw.edu', '../photos/enrollment/johanna-relkin.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAD6qmcBdXESLblm4Cwxcq-AQzexoG57ED2rJSulZnrW7A?e=istmOr', false, null, '{"Mentoring program operations"}', '{"Mentor required action completion rate","Mentor concern case QA"}'),
  (26, 'kimarie-howard', 'Kimarie Howard', 'Enrollment Counseling Development & Performance Coordinator', 'Contractor', null, 'rachel-kirk', 'enrollment', null, 5, 'khoward@byupw.edu', '../photos/enrollment/kimarie-howard.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQC8A6J14ltYSax9jMGUoFVTAec5lePpVzxNpeJdiJsbtBY?e=jimf3o', false, null, '{"Enrollment Counseling development and performance"}', '{"Enrollment Counseling CSAT rate","Enrollment Counseling yield contribution"}'),
  (27, 'megan-niblett', 'Megan Niblett', 'Enrollment Counseling Operations Coordinator', 'Contractor', null, 'rachel-kirk', 'enrollment', null, 5, 'megannicolebrown@byupw.edu', '../photos/enrollment/megan-niblett.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDYXALjqBy9TqMnkrLzZPALAVRIDVcR-t2zQ7_N6t_-sFI?e=OrqQzO', false, null, '{"Enrollment Counseling operations"}', '{"Enrollment Counseling required action completion rate","Enrollment Counseling contact rate by alert"}'),
  (28, 'shaunasee-james', 'Shaunasee Janette James', 'Enrollment Coordinator', 'FTE', null, 'trevor-shelton', 'enrollment', null, 5, 'scjames@byupw.edu', '../photos/enrollment/shaunasee-james.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBHJEF4d22UQ4TOTp6j8queASopK9ehmaq4-SfVdUQwo1g?e=qSPQFY', false, null, '{"Transfer evaluation","Ecclesiastical endorsement","Chaplain partnership"}', '{"Transfer evaluation processing rate","Number of transfer evaluation and endorsement cases","Transfer evaluation and endorsement case resolution rate"}'),
  (29, 'ely-zmolek', 'Ely Zmolek', 'Enrollment Coordinator', 'FTE', null, 'trevor-shelton', 'enrollment', null, 5, 'Elizabeth.Zmolek@byupw.edu', '../photos/enrollment/ely-zmolek.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDyS1zVpuz3SI8qQdzkXt4eAa5v6mtHteW4fZK3kCJ5twA?e=C1jcso', false, null, '{"Application processing","Admissons exceptions","Admissions systems"}', '{"Application processing rate","Application manual review turnaround rate","Number of admissions support cases","Admissions case resolution rate"}'),
  (30, 'anne-clark', 'Anne Marie Clark', 'Associate Dean of Students', 'FTE', null, 'steven-thomas', 'dean', null, 3, 'aclark@byupw.edu', '../photos/dean/anne-clark.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDSHzYkaQbiTKka4BszvUdeAelcwMltNNhbDXOi0SkDl08?e=xKEuAg', false, null, '{"Deputy Oversight of Title IX and ADA/Section 504 Compliance","Operational Governance and Quality Assurance of Dean of Students Services","Case Escalation, Secondary Review, and Risk Resolution Authority"}', '{"Dean of Students response and resolution time","Dean of Students services escalation rates","Partner C-Sat"}'),
  (31, 'katelyn-ray', 'Katelyn Ray', 'Student Honor & Conduct Coordinator', 'FTE', null, 'anne-clark', 'dean', null, 5, 'KRay@byupw.edu', '../photos/dean/katelyn-ray.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBQz2AWfHg4QLr-tLfqWB5OAfGlKm815bIjKlysE6sH3XU?e=12zTcP', false, null, '{"Institutional CES Honor Code Administration, Adjudication, and Due Process Enforcement","Behavioral Risk Monitoring and Institutional Conduct Trend Analysis"}', '{"Honor and Conduct response and resolution time","Repeat offender rate"}'),
  (32, 'sandra-wirttele', 'Sandra Wurttele', 'Accessibility Office Coordinator', 'Contractor', null, 'anne-clark', 'dean', null, 5, 'sandrawurttele@byupw.edu', '../photos/dean/sandra-wirttele.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBVF-cnaza5S4QpkfqcBzYBAeYcEuv3-9UQF2FsOVwDveg?e=fgld8E', false, null, '{"Disability Accommodation Determination and Deputy ADA/Section 504 Coordinator","Accommodation Appeals, Adjustments, and Compliance Documentation"}', '{"Accommodation determination processing and resolution rates","ADA and Section 504 standard compliance and audit compliance rates"}'),
  (33, 'ana-decastro', 'Ana De Castro', 'Office of Belonging Coordinator', 'FTE', null, 'anne-clark', 'dean', null, 5, 'Ana.deCastro@byupw.edu', '../photos/dean/ana-decastro.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDw3EYyUChUSY3A6NON-yzTAbsZyYTV79vgs6HuVXn3KPM?e=eMTFQX', false, null, '{"Non-Discrimination Administration and Institutional Response","Belonging-Related Concern Resolution and Systemic Risk Escalation"}', '{"Discrimination case resolution rate","Student sentiment on belonging","Student belonging CSAT"}'),
  (34, 'helen-reboucas', 'Helen Reboucas', 'Student Grievance Coordinator', 'Contractor', null, 'anne-clark', 'dean', null, 5, 'Helen.Reboucas@churchofjesuschrist.org', '../photos/dean/helen-reboucas.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAFWmgwRzlyR5zv2gsq5azrAXc2nfbXRXsAR85GuTJ0Ykw?e=lLfV4e', false, null, '{"Formal Student Grievance Administration and Due Process Assurance","Grievance Appeals, Pattern Analysis, and Institutional Risk Insight"}', '{"Student grievance case resolution time","Grievance QA"}'),
  (35, 'joseph-bentum', 'Joseph Bentum', 'Student Crisis Office Coordinator', 'Contractor', null, 'anne-clark', 'dean', null, 5, 'BentumJY@churchofjesuschrist.org', '../photos/dean/joseph-bentum.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCck7nWiNmJTbKblCL9bvWxASpttHquDaszNgyjwEDUvDA?e=zFBhpM', false, null, '{"Student Crisis Intake, Triage, Stabilization, and Emergency Coordination","High-Risk Case Monitoring and Institutional Safeguards"}', '{"Crisis response time"}'),
  (36, 'ricky-kailiponi', 'Ricky Kailiponi Jr.', 'Senior Manager of Digital Operations', 'FTE', null, 'jacob-adams', 'digital', null, 3, 'rkailiponi@byupw.edu', '../photos/digital/ricky-kailiponi.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQA_Pg4UzvhTS7QJCBFKoz33AfnpJQE-bSz0L_2WnenPqRk?e=fV14kS', false, null, '{"Business Partner collaboration","Architect & Engineer engagement (IT/ICS)","Development & QA lead","AI Compliance & advancement"}', '{"Team meeting project deadlines","Companion feature C-Sat","Companion usage rates","Companion C-Sat","AI retention effect"}'),
  (37, 'joshua-hadden', 'Joshua Stafford Hadden', 'System & Operations Manager', 'FTE', null, 'jacob-adams', 'digital', null, 3, 'jhadden@byupw.edu', '../photos/digital/joshua-hadden.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDAfxv5-z3nRIuCZ8cuqVLrAetuZhsS26bV2B5GVKjLtkk?e=we7VuH', false, null, '{"Registrar business solutions","Operational data & reporting","SIS support & configuration"}', '{"Team meeting project timelines rate","Stakeholder CSAT on team''s projects","Cost reductions in service areas (secondary)"}'),
  (38, 'sebastian-vargas', 'Sebastian Vargas', 'D365 & Automation Dev. Manager', 'Contractor', null, 'ricky-kailiponi', 'digital', null, 4, 'sebastian.vargas@ChurchofJesusChrist.org', '../photos/digital/sebastian-vargas.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCJXq3iu29QSbfipK9hj10LAboUgNxbbxhiZixIQKvTths?e=d8h5fW', false, null, '{"Mentor Portal","Predictive Model Data Pipeline"}', '{"Stakeholder CSAT - timeliness per project","Stakeholder CSAT - communication, quality of work, impact"}'),
  (39, 'samuel-riveros', 'Samuel Riveros', 'Companion & Special Projects Dev. Manager', 'Contractor', null, 'ricky-kailiponi', 'digital', null, 4, 'samuel.riveros@churchofjesuschrist.org', '../photos/digital/samuel-riveros.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAGDpuAcq_uRJQfBo6jtQ6VAZzICKfHCBKlonY8DuoA5c0?e=uOPRI1', false, null, '{"Companion Front-End Stability & Usability","Companion–Analytics Engine Integration"}', '{"Stakeholder CSAT - timeliness per project","Stakeholder CSAT - communication, quality of work, impact"}'),
  (40, 'aitana-toscano', 'Aitana Toscano', 'Data Manager', 'Contractor', null, 'joshua-hadden', 'digital', null, 4, 'Aitanantc@churchofjesuschrist.org', '../photos/digital/aitana-toscano.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDM61NrXoIgTZn7hTXqXYRFAT-HAogly8tB9cq40Uvl0dk?e=9icL1c', false, null, '{"Power BI reporting lead","Backend Data stability & cleaning"}', '{"Stakeholder CSAT - timeliness per project","Stakeholder CSAT - communication, quality of work, impact"}'),
  (41, 'isaias-zuniga', 'Isaias Zuñiga', 'AI Dev. Manager', 'Contractor', null, 'ricky-kailiponi', 'digital', null, 4, 'izunigac@byupw.edu', '../photos/digital/isaias-zuniga.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQB-HCg_VNVVQ6goimpZTa7rAZp194qZhHI9tyf41DYA3T4?e=9YCbey', false, null, '{"AI/ML Architecture development","Data Model development","Azure Board, GitHub, & DevOps Pipeline management"}', null),
  (42, 'david-peck', 'David Peck', 'Operational Data Analyst', 'FTE', null, 'joshua-hadden', 'digital', null, 5, 'dpeck@byupw.edu', '../photos/digital/david-peck.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQCZBbLkMAvERrRvFUiNIP8uAUhqA7Wc7H1tIJ0WisHWbLY?e=RulDks', false, null, '{"Power BI report management & refresh"}', '{"Project delivery on time rate","Stakeholder CSAT - communication, quality of work, impact"}'),
  (43, 'pelenatita-neiufi', 'Pelenatita Neiufi', 'Reporting & Evaluation Coordinator', 'FTE', null, 'joshua-hadden', 'digital', null, 5, 'PNeiufi@byupw.edu', '../photos/digital/pelenatita-neiufi.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQDO92S10jkTS7uQSURJg-AQAQB0pMN-87vTcDEJaGIc7Y8?e=m2YL0Q', false, null, '{"NSC & Enrollment reporting (BYUI & EC)","Student record updates (Demographics, SSN)","Qualitative research"}', '{"Project delivery on time rate","Stakeholder CSAT - communication, quality of work, impact"}'),
  (44, 'victor-ferreira', 'Victor Lamôni Calado Ferreira', 'System & Operations Associate Registrar', 'FTE', null, 'joshua-hadden', 'digital', null, 5, 'victorferreira@byupw.edu', '../photos/digital/victor-ferreira.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQBd6L0FnQgkQoq21Rr5e_CeAVnmrAepKNqoBsDZpFYsz3A?e=5EPfTL', false, null, '{"Registrar services for MLP students"}', '{"Project delivery on time rate","Stakeholder CSAT - communication, quality of work, impact"}'),
  (45, 'feyisayo-famakinde', 'Feyisayo Famakinde', 'Azure DevOps Engineer', 'Contractor', null, 'ricky-kailiponi', 'digital', null, 5, null, null, 'https://churchofjesuschrist.sharepoint.com/:w:/r/sites/BYU-PathwayStudentSuccessRoleInventory/_layouts/15/Doc.aspx?sourcedoc=%7B0C826DCB-21C5-423A-9C05-D7F3F0B32975%7D&file=Azure%20DevOps%20Engineer%20Role%20Inventory.docx&action=default&mobileredirect=true', false, null, null, null),
  (46, 'jess-swinburne', 'Jess Swinburne', 'Project Manager', 'Contractor', null, 'vp', 'executive', null, 2, 'JSwinburne@churchofjesuschrist.org', '../photos/executive/jess-swinburne.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Coordinate cross-departmental strategic initiatives for Student Services","Track project milestones, deliverables, and resource allocation across all departments","Facilitate executive reporting and stakeholder communication for the VP"}', '{"On-time delivery of cross-departmental projects","Stakeholder satisfaction with project communication and reporting","Resource utilization efficiency across initiatives"}'),
  (47, 'gilles-mambou', 'Elie Gilles Ravel Mambou', 'Assistant Project Manager', 'Contractor', null, 'jess-swinburne', 'executive', null, 2, 'gillesravelmambou@churchofjesuschrist.org', '../photos/executive/gilles-mambou.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Support project coordination and documentation for VP-level initiatives","Manage project timelines, meeting agendas, and action item tracking","Assist with cross-team communication and follow-up on deliverables"}', '{"Action item completion rate across VP initiatives","Meeting cadence adherence and documentation quality","Timely escalation of project risks and blockers"}'),
  (48, 'david-koomson', 'David De-Graft Koomson', 'Project Manager', 'Contractor', null, 'jacob-adams', 'digital', null, 3, 'davidkoomson@churchofjesuschrist.org', '../photos/executive/david-koomson.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'left', '{"Coordinate digital operations development and deployment projects","Track sprint deliverables, feature releases, and system integration milestones","Manage stakeholder reporting and project communication for digital initiatives"}', '{"On-time delivery of digital operations projects","Sprint and release milestone completion rate","Stakeholder satisfaction with project timeliness and communication"}'),
  (49, 'victor-elerunndu', 'Victor Oluwapelumi Elerunndu', 'Project Manager', 'Contractor', null, 'mark-gefrom', 'records', null, 3, 'oluwapelumi@churchofjesuschrist.org', '../photos/records/victor-elerunndu.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'left', '{"Coordinate student support improvement projects and initiatives","Track Help Center and ticket system optimization milestones","Manage cross-functional project timelines within student support operations"}', '{"On-time delivery of student support projects","Project milestone completion rate","Stakeholder satisfaction with project communication"}'),
  (50, 'moses-abioye', 'Moses Abioye', 'Project Manager', 'Contractor', null, 'mark-gefrom', 'records', null, 3, 'MAbioye@churchofjesuschrist.org', '../photos/records/moses-abioye.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Coordinate registration and records process improvement projects","Track registrar system updates and compliance initiative timelines","Manage project documentation and reporting for records operations"}', '{"On-time delivery of registrar and records projects","Registration process improvement milestones met","Project documentation completeness and accuracy"}'),
  (51, 'charles-crankson', 'Charles Crankson', 'Project Manager', 'Contractor', null, 'alison-cundiff', 'enrollment', null, 3, 'CCrankson@churchofjesuschrist.org', '../photos/enrollment/charles-crankson.jpg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Coordinate enrollment funnel and retention initiative projects","Track admissions system design, testing, and deployment milestones","Manage project reporting and cross-team coordination for enrollment services"}', '{"On-time delivery of enrollment and retention projects","Enrollment initiative milestone completion rate","Stakeholder satisfaction with project updates and communication"}'),
  (52, 'mariela-pezzali', 'Mariela Gisell Pezzali', 'Project Manager', 'Contractor', null, 'steven-thomas', 'dean', null, 3, 'MarielaPezzali@churchofjesuschrist.org', '../photos/dean/mariela-pezzali.png', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Coordinate Dean of Students office projects and compliance initiatives","Track Title IX, ADA/504, and student conduct process improvement timelines","Manage cross-office project documentation and stakeholder reporting"}', '{"On-time delivery of DOS compliance and policy projects","Project milestone completion rate for student services initiatives","Stakeholder satisfaction with project coordination and reporting"}'),
  (53, 'karina-vargas', 'Karina Andrea Vargas', 'Coordinator', 'Contractor', null, 'jacob-adams', 'digital', null, 3, 'karina_24@churchofjesuschrist.org', '../photos/digital/karina-vargas.jpeg', 'https://churchofjesuschrist.sharepoint.com/:w:/s/BYU-PathwayStudentSuccessRoleInventory/IQAmevpt63HgTreXjEGL0M9EAdyu6hNqyeGnyn7WtrmFhic?e=7CZh4x', true, 'right', '{"Coordinate digital operations development and deployment projects","Track sprint deliverables, feature releases, and system integration milestones","Manage stakeholder reporting and project communication for digital initiatives"}', '{"On-time delivery of digital operations projects","Sprint and release milestone completion rate","Stakeholder satisfaction with project timeliness and communication"}');

-- parent's display name, derived from the key so the two cannot disagree
update public.org_chart_nodes c
   set reports_to = p.name
  from public.org_chart_nodes p
 where c.reports_to_key = p.node_key;

-- long department name, for the pages that show it
update public.org_chart_nodes set department = case dept_slug
  when 'executive'  then 'VP - Student Services'
  when 'records'    then 'Student Records, Registration, and Support'
  when 'enrollment' then 'Enrollment & Retention'
  when 'dean'       then 'Dean of Students'
  when 'digital'    then 'Digital Operations'
  else department end;

-- put the sheet's stewardship / KPI wording back where the names match
update public.org_chart_nodes c
   set stewardships         = coalesce(c.stewardships, s.stewardships),
       key_kpis             = coalesce(c.key_kpis, s.key_kpis),
       key_responsibilities = coalesce(c.key_responsibilities, s.key_responsibilities),
       direct_reports       = coalesce(c.direct_reports, s.direct_reports)
  from _sheet_text s
 where lower(trim(c.name)) = s.name_key;

-- ── what the org chart page reads ─────────────────────────────────────────
create or replace view public.v_hub_org_chart as
  select node_key as id, name, role as title, dept_slug as dept, level,
         employee_status as status, reports_to_key as "reportsTo",
         coalesce(responsibilities, '{}') as responsibilities,
         coalesce(kpis, '{}') as kpis,
         email, photo_url as "photoUrl", link as "roleInventoryUrl",
         case when is_pm then 'pm' end as role_kind,
         pm_position as "pmPosition",
         stewardships, key_kpis, key_responsibilities, direct_reports
    from public.org_chart_nodes
   order by level, sort_order;

alter view public.v_hub_org_chart set (security_invoker = on);
grant select on public.v_hub_org_chart to anon, authenticated;

commit;
