"""
Bring the database's `employees` table up to the state the hub has been
maintained in, and write supabase/reconcile-directory.sql.

Why this exists: the Org Directory workbook was behind the hub. Several org
changes made over the past weeks — John Ayinde moving under Sebastian Vargas,
Aitana under Joshua Hadden, Kelley under Katelyn Graf, Katelyn and Charles being
added — lived only in directory/js/employees.js. Seeding from the workbook
silently reverted them.

Run once, apply the SQL, and the database becomes the source of truth from then
on. After that this script has no further use.

    python supabase/reconcile_directory.py
"""
import json
import re
import sys
import urllib.request
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
EMPLOYEES_JS = REPO / "directory" / "js" / "employees.js"
CONFIG_JS = REPO / "shared" / "js" / "config.js"
OUT = REPO / "supabase" / "reconcile-directory.sql"

FIELDS = [
    ("role", "role"),
    ("dept", "department"),
    ("type", "employment_type"),
    ("stakeholder", "primary_stakeholder"),
    ("subDept", "sub_department"),
    ("org", "contract_organization"),
    ("tier", "tier"),
]

# Names spelled differently in the workbook than in the hub. Left = database.
RENAMES = {
    "mandy schwab": "Mandy Poll Schwab",
    "johanna relkin": "Joanna Relken",
}


def sql(v):
    if v is None or v == "":
        return "null"
    return "'" + str(v).replace("'", "''") + "'"


def read_config():
    src = CONFIG_JS.read_text(encoding="utf-8")
    url = re.search(r'SUPABASE_URL:\s*"([^"]+)"', src).group(1)
    key = "".join(re.findall(r'"([A-Za-z0-9_\-\.]{20,})"', src.split("SUPABASE_ANON_KEY")[1]))
    return url.rstrip("/"), key


def fetch(url, key, path):
    req = urllib.request.Request(
        f"{url}/rest/v1/{path}",
        headers={"apikey": key, "Authorization": f"Bearer {key}"},
    )
    with urllib.request.urlopen(req, timeout=60) as r:
        return json.loads(r.read().decode())


def read_hub_employees():
    src = EMPLOYEES_JS.read_text(encoding="utf-8")
    out = []
    pattern = re.compile(
        r'\{\s*name:\s*"([^"]*)",\s*role:\s*"([^"]*)",\s*dept:\s*"([^"]*)",\s*'
        r'type:\s*"([^"]*)",\s*stakeholder:\s*"([^"]*)",\s*subDept:\s*"([^"]*)",\s*'
        r'org:\s*"([^"]*)",\s*tier:\s*"([^"]*)"\s*\}'
    )
    for m in pattern.finditer(src):
        name, role, dept, typ, stake, sub, org, tier = (g.strip() for g in m.groups())
        out.append({"name": name, "role": role, "dept": dept, "type": typ,
                    "stakeholder": stake, "subDept": sub, "org": org, "tier": tier})
    return out


def main():
    url, key = read_config()
    if not url or not key:
        sys.exit("Supabase is not configured in shared/js/config.js")

    hub = read_hub_employees()
    db = fetch(url, key, "employees?select=*")
    students = {s["name"].strip().lower() for s in fetch(url, key, "student_employees?select=name")}

    by_name = {e["name"].strip().lower(): e for e in db}
    # apply known renames so a spelling change isn't read as a new hire
    for old, new in RENAMES.items():
        if old in by_name:
            by_name[new.strip().lower()] = by_name[old]

    updates, inserts, renames = [], [], []
    max_sort = max((e.get("sort_order") or 0) for e in db) if db else 0

    def is_student(person, key_name):
        # The workbook doubles some surnames ("Jacob Keeney Keeney"), so match on
        # the first two words as well as the full name.
        if person.get("type", "").strip().lower() == "student employee":
            return True
        if key_name in students:
            return True
        short = " ".join(key_name.split()[:2])
        return any(s.startswith(short) for s in students)

    for person in hub:
        key_name = person["name"].strip().lower()
        if is_student(person, key_name):
            continue                     # belongs to student_employees
        row = by_name.get(key_name)
        if not row:
            max_sort += 1
            inserts.append((max_sort, person))
            continue

        if row["name"].strip() != person["name"].strip():
            renames.append((row["id"], row["name"], person["name"]))

        changes = {}
        for hub_field, col in FIELDS:
            want = (person.get(hub_field) or "").strip()
            have = (row.get(col) or "")
            have = have.strip() if isinstance(have, str) else have
            if str(want) != str(have or ""):
                changes[col] = want or None
        if changes:
            updates.append((row["id"], row["name"], changes))

    lines = [
        "-- ═══════════ DIRECTORY RECONCILIATION ═══════════\n"
        "-- Brings `employees` up to the org state the hub has been maintained in.\n"
        "-- The Org Directory workbook was behind on several reporting-line changes;\n"
        "-- seeding from it reverted them. Run this once, after seed.sql.\n"
        "-- Generated by supabase/reconcile_directory.py — safe to re-run.\n\n"
        "begin;\n\n"
    ]

    if renames:
        lines.append("-- Names spelled differently in the workbook\n")
        for rid, old, new in renames:
            lines.append(f"update public.employees set name = {sql(new)} where id = {rid};  -- was {old}\n")
        lines.append("\n")

    if updates:
        lines.append(f"-- {len(updates)} people whose details drifted\n")
        for rid, name, changes in updates:
            sets = ", ".join(f"{c} = {sql(v)}" for c, v in changes.items())
            lines.append(f"update public.employees set {sets} where id = {rid};  -- {name}\n")
        lines.append("\n")

    if inserts:
        lines.append(f"-- {len(inserts)} people missing from the workbook entirely\n")
        lines.append("insert into public.employees "
                     "(sort_order, name, role, department, employment_type, "
                     "primary_stakeholder, sub_department, contract_organization, tier) values\n")
        rows = []
        for order, p in inserts:
            rows.append("  (" + ", ".join([
                str(order), sql(p["name"]), sql(p["role"]), sql(p["dept"]), sql(p["type"]),
                sql(p["stakeholder"]), sql(p["subDept"]), sql(p["org"]), sql(p["tier"]),
            ]) + ")")
        lines.append(",\n".join(rows) + ";\n\n")

    lines.append("commit;\n")
    OUT.write_text("".join(lines), encoding="utf-8", newline="\n")

    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  renames  {len(renames)}")
    print(f"  updates  {len(updates)}")
    print(f"  inserts  {len(inserts)}")
    print()
    for rid, old, new in renames:
        print(f"  RENAME  {old}  ->  {new}")
    for _, name, changes in updates:
        for c, v in changes.items():
            print(f"  UPDATE  {name:32} {c:22} -> {v!r}")
    for _, p in inserts:
        print(f"  INSERT  {p['name']:32} {p['role']} ({p['dept']})")


if __name__ == "__main__":
    main()
