-- ═══════════ DIRECTORY RECONCILIATION ═══════════
-- Brings `employees` up to the org state the hub has been maintained in.
-- The Org Directory workbook was behind on several reporting-line changes;
-- seeding from it reverted them. Run this once, after seed.sql.
-- Generated by supabase/reconcile_directory.py — safe to re-run.

begin;

-- Names spelled differently in the workbook
update public.employees set name = 'Mandy Poll Schwab' where id = 71;  -- was Mandy Schwab

-- 50 people whose details drifted
update public.employees set role = 'AI Engineer' where id = 24;  -- Steven Tan
update public.employees set role = 'Team Lead' where id = 27;  -- Juan Camargo
update public.employees set role = 'Companion & Special Projects Dev. Manager', sub_department = 'Companion & Special Projects' where id = 28;  -- Samuel Riveros
update public.employees set role = 'Companion Native Developer, Security Champion', sub_department = 'Companion & Special Projects' where id = 29;  -- Jacob Sanchez
update public.employees set sub_department = 'Companion & Special Projects' where id = 30;  -- Valerie Sanchez
update public.employees set role = 'Companion Web Developer, Lead Designer', sub_department = 'Companion & Special Projects' where id = 31;  -- Michelle Gutierrez
update public.employees set role = 'Developer, QA Champion', sub_department = 'Companion & Special Projects' where id = 32;  -- Timileyin Omikunle
update public.employees set role = 'Team Lead, Companion Web & Native Developer', sub_department = 'Companion & Special Projects' where id = 33;  -- Alirio Mieres
update public.employees set role = 'Team Lead, Companion Web Developer', sub_department = 'Companion & Special Projects' where id = 34;  -- Ariel Sanchez
update public.employees set role = 'Team Lead, QA & Documentation', sub_department = 'Companion & Special Projects' where id = 35;  -- Gabriel Bolivar
update public.employees set role = 'D365 & Automation Dev. Team Lead', primary_stakeholder = 'Sebastian Vargas', sub_department = 'D365 & Automation' where id = 36;  -- John Ayinde
update public.employees set role = 'D365 & Automation Dev. Manager', sub_department = 'D365 & Automation' where id = 37;  -- Sebastian Vargas
update public.employees set primary_stakeholder = 'Sebastian Vargas', sub_department = 'D365 & Automation' where id = 38;  -- Matias Gutierrez
update public.employees set sub_department = 'D365 & Automation' where id = 39;  -- Elias Oyarzun
update public.employees set sub_department = 'D365 & Automation' where id = 40;  -- Ignacio Alvarez
update public.employees set sub_department = 'D365 & Automation' where id = 41;  -- Jose Sanchez
update public.employees set sub_department = 'D365 & Automation' where id = 42;  -- Rawin Olivera
update public.employees set sub_department = 'D365 & Automation' where id = 43;  -- Rene Sanchez
update public.employees set role = 'Azure DevOps Engineer' where id = 53;  -- Feyisayo Famakinde
update public.employees set role = 'System & Operations Manager' where id = 59;  -- Joshua Stafford Hadden
update public.employees set primary_stakeholder = 'Katelyn Graf' where id = 70;  -- Kelley Richardson
update public.employees set role = 'Mentoring Content Coordinator', employment_type = 'Professional Contractor', tier = '3' where id = 71;  -- Mandy Schwab
update public.employees set department = 'Student Records, Registration, and Support' where id = 77;  -- Moses Abioye
update public.employees set department = 'Student Records, Registration, and Support' where id = 78;  -- Victor Oluwapelumi Elerunndu
update public.employees set department = 'Student Records, Registration, and Support' where id = 79;  -- Mark Gefrom
update public.employees set department = 'Student Records, Registration, and Support' where id = 80;  -- Kim Overdiek
update public.employees set department = 'Student Records, Registration, and Support' where id = 81;  -- Tyson Bell
update public.employees set department = 'Student Records, Registration, and Support' where id = 82;  -- Angie Holt
update public.employees set department = 'Student Records, Registration, and Support' where id = 83;  -- Cindi C Putnam
update public.employees set department = 'Student Records, Registration, and Support' where id = 106;  -- Daniel Zago
update public.employees set department = 'Student Records, Registration, and Support' where id = 84;  -- Anne E. Owen
update public.employees set department = 'Student Records, Registration, and Support' where id = 85;  -- Kari Johnson
update public.employees set department = 'Student Records, Registration, and Support' where id = 86;  -- Nikki Jane Chambers
update public.employees set department = 'Student Records, Registration, and Support' where id = 87;  -- Kira Hayes
update public.employees set role = 'Senior Manager, Student Support', department = 'Student Records, Registration, and Support' where id = 88;  -- Brad Lester
update public.employees set department = 'Student Records, Registration, and Support' where id = 89;  -- Hilary Bagley
update public.employees set department = 'Student Records, Registration, and Support' where id = 90;  -- Alyssa Burrell
update public.employees set department = 'Student Records, Registration, and Support' where id = 91;  -- Adam Bradford
update public.employees set department = 'Student Records, Registration, and Support' where id = 92;  -- Armen Wood
update public.employees set department = 'Student Records, Registration, and Support' where id = 93;  -- Jackson Fonseca
update public.employees set department = 'Student Records, Registration, and Support' where id = 94;  -- Miguel Figuereo
update public.employees set department = 'Student Records, Registration, and Support' where id = 95;  -- Winner Aniekan Anietie
update public.employees set department = 'Student Records, Registration, and Support' where id = 100;  -- Colby Warner
update public.employees set department = 'Student Records, Registration, and Support' where id = 101;  -- Matthew Smith
update public.employees set primary_stakeholder = 'Joshua Stafford Hadden' where id = 58;  -- Aitana Nathaly Toscano Cedeño
update public.employees set department = 'Student Records, Registration, and Support' where id = 96;  -- Sariah De Hoyos Hernandez
update public.employees set department = 'Student Records, Registration, and Support' where id = 97;  -- Axel Dario Abalos
update public.employees set department = 'Student Records, Registration, and Support' where id = 98;  -- Maria Fernanda Moreno
update public.employees set department = 'Student Records, Registration, and Support' where id = 99;  -- Ana Laura Daniela Vasquez Reynoso
update public.employees set role = 'Assistant Project Manager', primary_stakeholder = 'Jess Swinburne' where id = 107;  -- Elie Gilles Ravel Mambou

-- Two people who were missing from the workbook when this file was written.
--
-- Guarded on name rather than inserted outright. The workbook has since been
-- corrected, so seed.sql now carries both — an unconditional insert here added
-- a second copy of each on any clean rebuild (111 employees instead of 109, and
-- two phantom rows on the KPI scorecard, which inner-joins employees). The
-- guard also makes this file safe to re-run, which it previously was not.
insert into public.employees (sort_order, name, role, department, employment_type, primary_stakeholder, sub_department, contract_organization, tier)
select 108, 'Charles Crankson', 'Project Manager', 'Enrollment & Retention', 'Professional Contractor', 'Alison Cundiff', 'Department Leadership', 'Springboard', '3'
 where not exists (select 1 from public.employees where lower(name) = 'charles crankson');

insert into public.employees (sort_order, name, role, department, employment_type, primary_stakeholder, sub_department, contract_organization, tier)
select 109, 'Katelyn Graf', 'Senior Manager of Retention', 'Enrollment & Retention', 'Full-Time Employee', 'Alison Cundiff', 'Retention', null, null
 where not exists (select 1 from public.employees where lower(name) = 'katelyn graf');


-- The hub's directory lists staff and student employees together; the original
-- view returned staff only, which dropped 85 people from that page.
create or replace view public.v_hub_directory as
  select name, role, department as dept, employment_type as type,
         primary_stakeholder as stakeholder, sub_department as "subDept",
         contract_organization as org, tier
  from public.employees
  where active
  union all
  select name, coalesce(role_title, job_name) as role, department as dept,
         'Student Employee' as type, supervisor as stakeholder,
         sub_department as "subDept", null as org, null as tier
  from public.student_employees
  where active
  order by dept, "subDept", name;

grant select on public.v_hub_directory to anon, authenticated;

commit;
