/* ═══════════════════════════════════════════════════════════════
   SHARED EMPLOYEE DATA — SINGLE SOURCE OF TRUTH

   Edit this file to add, remove, or update any employee. Every page
   that shows employee data reads from this same file, so one edit
   propagates everywhere automatically:

     • Student Services Directory  → /directory/index.html
     • Dean of Students            → /departments/dean.html
     • Digital Operations          → /departments/digital.html
     • Enrollment & Retention      → /departments/enrollment.html
     • Records, Registration...    → /departments/records.html

   Each dept page filters this array by `dept` at page load, so any
   change here updates that dept's KPIs, sub-dept bar chart, and
   employment-type donut on the next refresh.
   ═══════════════════════════════════════════════════════════════ */
window.EMPLOYEES = [
  { name: "Gisele Loisotto", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Sandra Wurttele", subDept: "Accessibility Office", org: "Springboard", tier: "3" },
  { name: "Sandra Wurttele", role: "Accessibility Office Coordinator", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Anne Marie Clark", subDept: "Department Leadership", org: "Velocity Global - EOR", tier: "EOR" },
  { name: "Ana de Castro", role: "Office of Belonging Coordinator", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Anne Marie Clark", subDept: "Department Leadership", org: "Velocity Global - EOR", tier: "EOR" },
  { name: "Mariela Pezzali", role: "Project Manager", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Steven K. Thomas", subDept: "Department Leadership", org: "Springboard", tier: "3.5" },
  { name: "Joseph Bentum", role: "Student Crisis Office Coordinator", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Anne Marie Clark", subDept: "Department Leadership", org: "XML- EOR", tier: "EOR" },
  { name: "Helen Segalla de Oliveira Rebouças", role: "Student Grievance Coordinator", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Anne Marie Clark", subDept: "Department Leadership", org: "Springboard", tier: "3.5" },
  { name: "Anne Marie Clark", role: "Associate Dean of Students", dept: "Dean of Students", type: "Full-Time Employee", stakeholder: "Steven K. Thomas", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Steven K. Thomas", role: "Dean of Students", dept: "Dean of Students", type: "Full-Time Employee", stakeholder: "VP of Student Services", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Joseph Chingwara", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Helen Segalla de Oliveira Rebouças", subDept: "Grievance Office", org: "Springboard", tier: "3" },
  { name: "Ifunanya Queendalyn Okeke", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Helen Segalla de Oliveira Rebouças", subDept: "Grievance Office", org: "Springboard", tier: "3" },
  { name: "Wesley dos Santos", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Helen Segalla de Oliveira Rebouças", subDept: "Grievance Office", org: "Springboard", tier: "3" },
  { name: "Katelyn Ray", role: "Student Honor & Conduct Coordinator", dept: "Dean of Students", type: "Full-Time Employee", stakeholder: "Anne Marie Clark", subDept: "Service Area Coordinators", org: "", tier: "" },
  { name: "Scott Appiah", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Joseph Bentum", subDept: "Student Crisis Office", org: "Springboard", tier: "3" },
  { name: "Tubo-Oreriba Joseph Elisha", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Joseph Bentum", subDept: "Student Crisis Office", org: "Springboard", tier: "3" },
  { name: "Israel Juzgaya", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Katelyn Ray", subDept: "Student Honor & Conduct Office", org: "Springboard", tier: "3" },
  { name: "Rhoda Mabundu", role: "Dean of Students Office Specialist", dept: "Dean of Students", type: "Professional Contractor", stakeholder: "Katelyn Ray", subDept: "Student Honor & Conduct Office", org: "Springboard", tier: "3" },
  { name: "Isaias Zuñiga", role: "AI Dev. Manager", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ricky Kailiponi Jr.", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Diego Huarsaya", role: "AI Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Jorge Chavez", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Jorge Sosa", role: "AI Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Isaias Zuñiga", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Steven Tan", role: "AI Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Juan Camargo", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Prosper Odinakachukwu", role: "AI Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Juan Camargo", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Jorge Chavez", role: "Team Lead", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Isaias Zuñiga", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Juan Camargo", role: "Team Lead", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Isaias Zuñiga", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Brandot Yarleque", role: "AI Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Isaias Zuñiga", subDept: "AI", org: "Upwork", tier: "3" },
  { name: "Samuel Riveros", role: "Companion & Special Projects Dev. Manager", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ricky Kailiponi Jr.", subDept: "Companion & Special Projects", org: "Springboard", tier: "3" },
  { name: "Jacob Sanchez", role: "Companion Native Developer, Security Champion", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Alirio Mieres", subDept: "Companion & Special Projects", org: "Upwork", tier: "3" },
  { name: "Valerie Sanchez", role: "Companion Web Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ariel Sanchez", subDept: "Companion & Special Projects", org: "Upwork", tier: "3" },
  { name: "Michelle Gutierrez", role: "Companion Web Developer, Lead Designer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ariel Sanchez", subDept: "Companion & Special Projects", org: "Upwork", tier: "3" },
  { name: "Timileyin Omikunle", role: "Developer, QA Champion", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Gabriel Bolivar", subDept: "Companion & Special Projects", org: "Upwork", tier: "3" },
  { name: "Alirio Mieres", role: "Team Lead, Companion Web & Native Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Samuel Riveros", subDept: "Companion & Special Projects", org: "Upwork", tier: "3" },
  { name: "Ariel Sanchez", role: "Team Lead, Companion Web Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Samuel Riveros", subDept: "Companion & Special Projects", org: "Springboard", tier: "3" },
  { name: "Gabriel Bolivar", role: "Team Lead, QA & Documentation", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Samuel Riveros", subDept: "Companion & Special Projects", org: "Springboard", tier: "3" },
  { name: "John Ayinde", role: "Team Lead", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Sebastian Vargas", subDept: "D365 & Automation", org: "Springboard", tier: "3" },
  { name: "Sebastian Vargas", role: "D365 & Automation Dev. Manager", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ricky Kailiponi Jr.", subDept: "D365 & Automation", org: "Springboard", tier: "3" },
  { name: "Matias Gutierrez", role: "Team Lead", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Sebastian Vargas", subDept: "D365 & Automation", org: "Springboard", tier: "3" },
  { name: "Elias Oyarzun", role: "PowerApps Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Matias Gutierrez", subDept: "D365 & Automation", org: "Upwork", tier: "3" },
  { name: "Ignacio Alvarez", role: "PowerApps Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Sebastian Vargas", subDept: "D365 & Automation", org: "Upwork", tier: "3" },
  { name: "Jose Sanchez", role: "PowerApps Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Matias Gutierrez", subDept: "D365 & Automation", org: "Upwork", tier: "3" },
  { name: "Rawin Olivera", role: "PowerApps Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Sebastian Vargas", subDept: "D365 & Automation", org: "Springboard", tier: "3" },
  { name: "Rene Sanchez", role: "PowerApps Developer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Sebastian Vargas", subDept: "D365 & Automation", org: "Upwork", tier: "3" },
  { name: "James De Guzman", role: "Analytics & Automation Specialist", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Upwork", tier: "3" },
  { name: "Dulci Dos Santos", role: "Team Lead", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Springboard", tier: "3" },
  { name: "Gonzalo Oyarzun", role: "Data Analyst & Reporting Specialist", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Upwork", tier: "3" },
  { name: "Nefi Dorado", role: "Data Analyst & Reporting Specialist", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Upwork", tier: "3" },
  { name: "Oluwatobi Makinde", role: "Data Analyst & Reporting Specialist", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Upwork", tier: "3" },
  { name: "Goodness Okafor", role: "Data Pipeline Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Dulci Dos Santos", subDept: "Data", org: "Upwork", tier: "3" },
  { name: "Matias Valenzuela", role: "ML Specialist (Predictive Models)", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Aitana Toscano", subDept: "Data", org: "Springboard", tier: "3" },
  { name: "Jacob Adams", role: "Director of Digital Operations", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "VP of Student Services", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Ricky Kailiponi Jr.", role: "Senior Manager of Digital Operations", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "Jacob Adams", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Feyisayo Famakinde", role: "Azure Dev Ops Engineer", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ricky Kailiponi Jr.", subDept: "Dev-Ops", org: "Upwork", tier: "3" },
  { name: "Karina Vargas", role: "Coordinator", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Ricky Kailiponi Jr.", subDept: "Project Management", org: "Upwork", tier: "3" },
  { name: "David Peck", role: "Operational Data Analyst", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "Joshua Stafford Hadden", subDept: "Systems & Operations", org: "", tier: "" },
  { name: "Pelenatita Neiufi", role: "Reporting & Evaluation Coordinator", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "Joshua Stafford Hadden", subDept: "Systems & Operations", org: "", tier: "" },
  { name: "Victor Lamôni Calado Ferreira", role: "System & Operations Associate Registrar", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "Joshua Stafford Hadden", subDept: "Systems & Operations", org: "", tier: "" },
  { name: "Joshua Stafford Hadden", role: "System & Operations Manager", dept: "Digital Operations", type: "Full-Time Employee", stakeholder: "Jacob Adams", subDept: "Systems & Operations", org: "", tier: "" },
  { name: "Terence Borjal", role: "Qualitative Researcher", dept: "Digital Operations", type: "Professional Contractor", stakeholder: "Joshua Stafford Hadden", subDept: "Systems & Operations", org: "Springboard", tier: "3" },
  { name: "James Etukudo", role: "Project Manager", dept: "Enrollment & Retention", type: "Professional Contractor", stakeholder: "Alison Cundiff", subDept: "Department Leadership", org: "Springboard", tier: "3" },
  { name: "Alison Cundiff", role: "Director of Enrollment & Retention", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "VP of Student Services", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Jose Escoto", role: "Senior Success Manager for Enrollment Counselling", dept: "Enrollment & Retention", type: "Professional Contractor", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "Springboard", tier: "3" },
  { name: "Rachel Kirk", role: "Enrollment Counseling Manager", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "Alison Cundiff", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Kimarie Howard", role: "Enrollment Counseling Development & Performance Coordinator", dept: "Enrollment & Retention", type: "Part-Time Temporary", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Megan Niblett", role: "Enrollment Counseling Operations Coordinator", dept: "Enrollment & Retention", type: "Part-Time Temporary", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Shaunasee Janette James", role: "Enrollment Coordinator", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "Trevor Shelton", subDept: "Enrollment Services", org: "", tier: "" },
  { name: "Ely Zmolek", role: "Enrollment Coordinator", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "Trevor Shelton", subDept: "Enrollment Services", org: "", tier: "" },
  { name: "Trevor Shelton", role: "Senior Manager of Enrollment Services", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "Alison Cundiff", subDept: "Enrollment Services", org: "", tier: "" },
  { name: "Peter Abarte", role: "Senior Success Manager for Mentoring", dept: "Enrollment & Retention", type: "Professional Contractor", stakeholder: "Kelley Richardson", subDept: "Mentoring", org: "Springboard", tier: "3" },
  { name: "Kelley Richardson", role: "Mentoring Manager", dept: "Enrollment & Retention", type: "Full-Time Employee", stakeholder: "Alison Cundiff", subDept: "Mentoring", org: "", tier: "" },
  { name: "Mandy Schwab", role: "Mentor Development Specialist", dept: "Enrollment & Retention", type: "Part-Time Temporary", stakeholder: "Kelley Richardson", subDept: "Mentoring", org: "", tier: "" },
  { name: "Joanna Relken", role: "Mentor Operations Specialist", dept: "Enrollment & Retention", type: "Part-Time Temporary", stakeholder: "Kelley Richardson", subDept: "Mentoring", org: "", tier: "" },
  { name: "Moses Abioye", role: "Project Manager", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Mark Gefrom", subDept: "Department Leadership", org: "Springboard", tier: "3" },
  { name: "Victor Oluwapelumi Elerunndu", role: "Project Manager", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Mark Gefrom", subDept: "Department Leadership", org: "Springboard", tier: "3" },
  { name: "Mark Gefrom", role: "Director of Student Records, Registration & Support", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "VP of Student Services", subDept: "Department Leadership", org: "", tier: "" },
  { name: "Kim Overdiek", role: "Associate Registrar (Curriculum & Configuration)", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Kari Johnson", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Tyson Bell", role: "Associate Registrar (Transcripts & Graduation)", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Kari Johnson", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Geraldine Susan Bean", role: "Graduation Coordinator", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Cindi C Putnam", role: "Planning Coordinator", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Kim Overdiek", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Anne E. Owen", role: "Records & Transcript Coordinator", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Kari Johnson", role: "Registrar", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Mark Gefrom", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Nikki Jane Chambers", role: "Enrollment Verification Specialist", dept: "Student Records, Registration, and Support", type: "Full-Time Temporary", stakeholder: "Kim Overdiek", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Kira Hayes", role: "Consistency Coordinator (QA & Knowledge Base)", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Hilary Bagley", subDept: "Student Support", org: "", tier: "" },
  { name: "Brad Lester", role: "General Support Manager", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Mark Gefrom", subDept: "Student Support", org: "", tier: "" },
  { name: "Hilary Bagley", role: "Student Experience Coordinator", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Brad Lester", subDept: "Student Support", org: "", tier: "" },
  { name: "Alyssa Burrell", role: "Student Support Coordinator (Phone Support)", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Brad Lester", subDept: "Student Support", org: "", tier: "" },
  { name: "Adam Bradford", role: "Technical Support Engineer", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "Upwork", tier: "3" },
  { name: "Armen Wood", role: "Technical Support Engineer", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "Upwork", tier: "3" },
  { name: "Jackson Fonseca", role: "Technical Support Engineer", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "Springboard", tier: "3" },
  { name: "Miguel Figuereo", role: "Technical Support Engineer", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "Upwork", tier: "3" },
  { name: "Winner Aniekan Anietie", role: "Technical Support Engineer", dept: "Student Records, Registration, and Support", type: "Professional Contractor", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "Springboard", tier: "3" },
  { name: "Colby Warner", role: "Product Support Engineer", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Matthew Smith", subDept: "Technical Support", org: "", tier: "" },
  { name: "Matthew Smith", role: "Technical Support Manager", dept: "Student Records, Registration, and Support", type: "Full-Time Employee", stakeholder: "Mark Gefrom", subDept: "Technical Support", org: "", tier: "" },
  { name: "David De-Graft Koomson", role: "Assistant Project Manager", dept: "VP - Student Services", type: "Professional Contractor", stakeholder: "Jess Swinburne", subDept: "Department Leadership", org: "Springboard", tier: "3" },
  { name: "Jess Swinburne", role: "Project Manager", dept: "VP - Student Services", type: "Professional Contractor", stakeholder: "Ben Packer", subDept: "Department Leadership", org: "Springboard", tier: "3" },

  /* ═══════════════ STUDENT EMPLOYEES ═══════════════ */
  { name: "Abish Arroyo Avila", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Abraham Osorio", role: "Planning Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Adolfo Arellano Pineda", role: "Student Data evaluator", dept: "Digital Operations", type: "Student Employee", stakeholder: "Pelenatita Neiufi", subDept: "Data", org: "", tier: "" },
  { name: "Aida Camarillo", role: "Records & Transcripts Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Anne E. Owen", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Alan Sanchez", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Alana Willis", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Alejandro Alvarez Flores", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Alejandro Gonzalez", role: "Records & Transcripts Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Anne E. Owen", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Amanda Smith", role: "Graduation Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Andrew Petersen", role: "Graduation Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Angie Holt", role: "Graduation Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Arian Bazan Azanero", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Ashley Currier", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Astrid Rivera Nunez", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Brett Lyman", role: "Registration Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Kim Overdiek", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Brooklyn Craythorne", role: "Hiring Manager", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Bruce Holway", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Chhung Kim", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Daniel Rasmuson", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Daniela Santibanez Pineira", role: "Graduation Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Derek Goodwin", role: "Graduation Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Destiny Hardin", role: "Enrollment Verification Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Eduardo Sulecio", role: "Registration Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Kim Overdiek", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Elizabeth Anthony", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Elizabeth DeGraw", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Emilly Ferreira Lima Durante", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Emma Hamblin", role: "Enrollment Verification Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Ethan Brockbank", role: "Graduation Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Grover Vasquez", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Jackson Campbell", role: "Planning Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Jerry Hodges", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Jimena Martinez Bolanos", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Jonah Christensen", role: "Enrollment Verification Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Joshua Jones", role: "Graduation Diplomatic Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Juliana Daley", role: "Enrollment Verification Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Kami Mitchell", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Kate DeForest", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Kathy Norcross", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Kayla Palmore", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Letitia Marshall-Mellor", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Lillian Rousseau", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Livvy Rodarte", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Makenna Lundquist", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Mandy Hatch", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Marilin Mullo Culquicondor", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Melchisedek Davila Mata", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Milagros Concha Tamo", role: "Student Data Enaluator", dept: "Digital Operations", type: "Student Employee", stakeholder: "Anne E. Owen", subDept: "Data", org: "", tier: "" },
  { name: "Misael Iniestra Salazar", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Morgan Beckey", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Morgan Bohne", role: "Records & Transcripts Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Anne E. Owen", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Morgan Redd", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Nina Eubanks", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Olivia Cordero", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Paige Petersen", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Paige Rasmussen", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Rachel Dowdle", role: "Planning Supervisor", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Rebeca Cisneros Lozano", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Rebeca Leite", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Reina Matsumura", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Sarah Birmingham", role: "Enrollment Verification Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Sarah Purvis", role: "Enrollment Verification Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Nikki Jane Chambers", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Tarali Blanchard", role: "Transfer Evaluation Agent", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Shaunasee Janette James", subDept: "Transfer Evaluation", org: "", tier: "" },
  { name: "Valeria Morales Pontillo", role: "Planning Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Vanessa Sales de Morais", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Vincent Onen", role: "Graduation Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Tyson Bell", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Yessika Antillon Denison Denison", role: "Planning Shift Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Cindi C Putnam", subDept: "Registrar's Office", org: "", tier: "" },
  { name: "Alessandra Loiola", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Awilda Santos", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Blake Call", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Connor Washburn", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Endrit Cakollari", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Felipe Feitosa", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Horace Tun", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Isis Flores", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Jassive Duran", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Katelyn Slaugh", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Kira Odake", role: "Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Madi Bell", role: "Domestic Phone Support Lead", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Mami Nagata", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Marquelle Call", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Mia Homer", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Natalia Iglesias Vinocuna", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Nick Gonzalez", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Paige Gunther", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Stella Gefrom", role: "Domestic Phone Support Agent", dept: "Student Records, Registration, and Support", type: "Student Employee", stakeholder: "Alyssa Burrell", subDept: "Student Support", org: "", tier: "" },
  { name: "Aubrey Smith", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Bradley Braganca", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Char Fridley", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Daniel Leal", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Doris Klinglesmith", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Jacob Keeney", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Kim Stewart", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Mack Monson", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Patricia Ann Donato", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Rebekah Sasser", role: "Domestic Enrollment Counselor", dept: "Enrollment & Retention", type: "Student Employee", stakeholder: "Rachel Kirk", subDept: "Enrollment Counseling", org: "", tier: "" },
  { name: "Melyssa Silva", role: "Student Data evaluator", dept: "Digital Operations", type: "Student Employee", stakeholder: "Pelenatita Neiufi", subDept: "Data", org: "", tier: "" },
];

/* ═══════════════ BYU-PATHWAY DEPT COLORS ═══════════════ */
window.DEPT_COLORS = {
  "Dean of Students":                 { bg: "#A2C23D", light: "#8aaa2e", pale: "#f2f7e6", r: "162,194,61" },
  "Digital Operations":               { bg: "#CB4A27", light: "#a83d20", pale: "#fbeee9", r: "203,74,39" },
  "Enrollment & Retention":           { bg: "#B687AC", light: "#9a6f90", pale: "#f5edf3", r: "182,135,172" },
  "Student Records, Registration, and Support":  { bg: "#3A929D", light: "#2a7a84", pale: "#e8f4f5", r: "58,146,157" },
  "VP - Student Services":            { bg: "#FFC328", light: "#d4a020", pale: "#fff6d6", r: "255,195,40" },
};

window.TYPE_COLORS = {
  "Full-Time Employee":      "#065577",
  "Full-Time Temporary":     "#28738A",
  "Part-Time Temporary":     "#FFC328",
  "Professional Contractor": "#7F898A",
  "Student Contractor":      "#B687AC",
  "Student Employee":        "#5E60CE",
};

/* ═══════════════ STUDENT CONTRACTOR AGGREGATE COUNTS ═══════════════
   Counts only — student contractors aren't tracked individually here,
   so they don't appear in the directory table or per-person filters.
   These feed the dedicated "Student Contractors" card on the page. */
window.STUDENT_CONTRACTORS = {
  "Student Records, Registration, and Support": 338,
  "Enrollment & Retention":                     455,
  "Digital Operations":                         0,
  "Dean of Students":                           0,
};
